/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DefaultSidebar: typeof import('./src/components/sidebars/DefaultSidebar.vue')['default']
    'IEva:arrowBackOutline': typeof import('~icons/eva/arrow-back-outline')['default']
    'IFaBrands:github': typeof import('~icons/fa-brands/github')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}
