description: Update models doc
prompt: |-
      I have these files:

      ```
      {prompt}
      ```

      Rewrite models.md to update the models names in the relevant sections from the information in the yaml files. Use only the information from the yaml files as source of truth: the available models names actually in models.md are outdated. Rewrite from the yaml files only: use all the models names from the yaml files
template: 
    system: |- 
        You are an AI programmer assistant. Your task is to write and update documentation.
ctx: 32768
model:
  name: qwen2.5-coder:32b-instruct-q8_0
  template: chatml
 
inferParams:
    top_p: 1
    top_k: 0
    min_p: 0.05
    temperature: 0
    max_tokens: 8192